library(DBI)
library(RSQLite)
drv <- dbDriver("SQLite")
con <- dbConnect(drv, dbname = "chinook.db" )
dbListTables(con)
Q1 <- dbGetQuery(con, "SELECT* FROM Track ORDER By Milliseconds")
Q2 <- dbGetQuery(con, "SELECT CustomerId, SUM(Total) FROM Invoice GROUP BY CustomerID HAVING SUM(Total) > 40")
Q3 <- dbGetQuery(con, "SELECT artistid FROM artist WHERE name ='QUEEN'")
Q4 <- dbGetQuery(con, "SELECT* FROM track ORDER By milliseconds LIMIT 10")
Q5 <- dbGetQuery(con, "SELECT title, name FROM album JOIN track USING(albumid) WHERE unitprice = 1.99")
Q6 <- dbGetQuery(con, "SELECT artist.name, title, SUM(milliseconds)/1000 AS Length FROM album JOIN artist USING (artistid) JOIN track USING (albumid) GROUP By albumid HAVING length > 1000 ORDER BY Length DESC")
Q7 <- dbGetQuery(con, "SELECT customer.lastname, customer.firstname, track.name, invoiceline.quantity, invoiceline.unitprice FROM customer JOIN invoice USING(customerID) JOIN invoiceline USING (Invoiceid) JOIN track USING(trackid)")
Q8 <- dbGetQuery(con, "SELECT DISTINCT customer.* FROM customer JOIN invoice AS T1 USING (customerid) JOIN invoice AS T2 USING (customerid) WHERE T1.total >10 AND T2.total >10 AND T1.invoiceid != T2.invoiceid")
dbDisconnect(con)
